---
deployment:
  tasks:
    - export DEPLOYPATH=/home/sumahond/public_html/
    - /bin/cp -R public/* $DEPLOYPATH
    - export DEPLOYPATH=/home/sumahond/public_html/assets
    - /bin/cp -R public/assets/* $DEPLOYPATH
    - export DEPLOYPATH=/home/sumahond/public_html/vendor
    - /bin/cp -R public/vendor/* $DEPLOYPATH
    - export DEPLOYPATH=/home/sumahond/public_html/storage
    - /bin/cp -R public/storage/* $DEPLOYPATH
